variable "enabled" {
  type        = bool
  description = "Set to false to prevent the module from creating any resources"
  default     = true
}

variable "name" {
  type        = string
  description = "The name of the SAML provider to create"
}

variable "saml_metadata_document" {
  type        = string
  description = "An XML document generated by an identity provider that supports SAML 2.0"
}

variable "tags" {
  type        = map(string)
  description = "A map of tags to add to all resources"
  default     = {}
}
